/**
 * Device Permissions & Privacy Helper
 * 
 * This module provides utilities to determine which device properties
 * require user consent or system permissions.
 */

export type DeviceProperty = 
  | 'deviceCategory'
  | 'deviceBrand'
  | 'locale'
  | 'language'
  | 'timeZone'
  | 'timeZoneOffset'
  | 'advertisingId'
  | 'vendorId'
  | 'limitedAdTracking'
  | 'appId'
  | 'appInstanceId'
  | 'firstOpenAt'
  | 'firstPurchaseAt'

export interface PermissionRequirement {
  property: DeviceProperty
  requiresConsent: boolean
  requiresSystemPermission: boolean
  platform: 'ios' | 'android' | 'both'
  description: string
  privacyNote: string
}

/**
 * Permission requirements for each device property
 */
export const DEVICE_PROPERTY_PERMISSIONS: PermissionRequirement[] = [
  {
    property: 'deviceCategory',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Device category (mobile, tablet, desktop, tv) - determined from screen size',
    privacyNote: 'No permission or consent required. Can be determined from device characteristics.'
  },
  {
    property: 'deviceBrand',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Device brand (Samsung, Apple, Google, etc.)',
    privacyNote: 'No permission or consent required. Available via device info APIs.'
  },
  {
    property: 'locale',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Device locale (en-US, fr-FR, etc.)',
    privacyNote: 'No permission or consent required. System locale setting.'
  },
  {
    property: 'language',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Device language code (en, fr, etc.)',
    privacyNote: 'No permission or consent required. System language setting.'
  },
  {
    property: 'timeZone',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Device timezone (America/New_York, Europe/London, etc.)',
    privacyNote: 'No permission or consent required. System timezone setting.'
  },
  {
    property: 'timeZoneOffset',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Timezone offset in seconds from UTC',
    privacyNote: 'No permission or consent required. Calculated from timezone.'
  },
  {
    property: 'appId',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'App ID / Package name / Bundle ID',
    privacyNote: 'No permission or consent required. App metadata.'
  },
  {
    property: 'appInstanceId',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'App instance identifier (similar to Firebase Installation ID)',
    privacyNote: 'No permission or consent required. Generated by SDK.'
  },
  {
    property: 'firstOpenAt',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'First time app was opened on this device',
    privacyNote: 'No permission or consent required. App-level tracking.'
  },
  {
    property: 'firstPurchaseAt',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'First purchase timestamp (if applicable)',
    privacyNote: 'No permission or consent required. App-level tracking.'
  },
  {
    property: 'vendorId',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Vendor ID (Android ID, iOS IDFV)',
    privacyNote: 'No explicit consent required, but should be disclosed in privacy policy. Considered personal data under GDPR. iOS IDFV is privacy-friendly alternative to IDFA.'
  },
  {
    property: 'limitedAdTracking',
    requiresConsent: false,
    requiresSystemPermission: false,
    platform: 'both',
    description: 'Limited Ad Tracking status',
    privacyNote: 'No permission needed to check this status. Should be checked before using advertisingId.'
  },
  {
    property: 'advertisingId',
    requiresConsent: true,
    requiresSystemPermission: true,
    platform: 'both',
    description: 'Advertising ID (GAID on Android, IDFA on iOS)',
    privacyNote: 'REQUIRES EXPLICIT USER CONSENT. iOS requires ATT framework. Android requires GDPR/CCPA compliance. Must respect user\'s ad personalization settings.'
  }
]

/**
 * Get permission requirements for a specific property
 */
export function getPropertyPermission(property: DeviceProperty): PermissionRequirement | undefined {
  return DEVICE_PROPERTY_PERMISSIONS.find(p => p.property === property)
}

/**
 * Get all properties that require user consent
 */
export function getPropertiesRequiringConsent(): DeviceProperty[] {
  return DEVICE_PROPERTY_PERMISSIONS
    .filter(p => p.requiresConsent)
    .map(p => p.property)
}

/**
 * Get all properties that require system permissions
 */
export function getPropertiesRequiringSystemPermission(): DeviceProperty[] {
  return DEVICE_PROPERTY_PERMISSIONS
    .filter(p => p.requiresSystemPermission)
    .map(p => p.property)
}

/**
 * Get all properties that can be collected without consent
 */
export function getPropertiesNoConsentRequired(): DeviceProperty[] {
  return DEVICE_PROPERTY_PERMISSIONS
    .filter(p => !p.requiresConsent && !p.requiresSystemPermission)
    .map(p => p.property)
}

/**
 * Validate if a property can be collected based on consent status
 */
export function canCollectProperty(
  property: DeviceProperty,
  hasConsent: boolean = false
): { canCollect: boolean; reason?: string } {
  const requirement = getPropertyPermission(property)
  
  if (!requirement) {
    return { canCollect: false, reason: 'Unknown property' }
  }
  
  if (requirement.requiresConsent && !hasConsent) {
    return {
      canCollect: false,
      reason: `${property} requires explicit user consent`
    }
  }
  
  return { canCollect: true }
}

